apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebraska-app.fullname" . }}-aws
  labels:
    {{- include "nebraska-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.dynamodb.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.dynamodb.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.dynamodb.region | quote }}
  AWS_ENDPOINT_URL_DYNAMODB: {{ include "nebraska-app.dynamodbEndpoint" . | quote }}
