apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebraska-app.fullname" . }}-aws
  labels:
    {{- include "nebraska-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.dynamodb.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.dynamodb.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.dynamodb.region | quote }}
  AWS_ENDPOINT_URL_DYNAMODB: {{ include "nebraska-app.dynamodbEndpoint" . | quote }}
{{- if not .Values.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebraska-app.fullname" . }}-auth
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.auth.sessionSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
  VIEWER_PASSWORD: {{ .Values.auth.viewerPassword | quote }}
{{- end }}
